import { WORKSPACE_ROLES, type WorkspaceRole, PLATFORM_ROLES } from './roles';

export const PERMISSIONS = {
  // Platform admin permissions
  PLATFORM_TENANTS_VIEW: 'platform:tenants:view',
  PLATFORM_TENANTS_MANAGE: 'platform:tenants:manage',
  PLATFORM_TENANTS_DELETE: 'platform:tenants:delete',
  PLATFORM_USERS_VIEW: 'platform:users:view',
  PLATFORM_USERS_MANAGE: 'platform:users:manage',
  PLATFORM_USERS_DELETE: 'platform:users:delete',
  PLATFORM_BILLING_VIEW: 'platform:billing:view',
  PLATFORM_BILLING_MANAGE: 'platform:billing:manage',
  PLATFORM_BILLING_REFUND: 'platform:billing:refund',
  PLATFORM_WHATSAPP_VIEW: 'platform:whatsapp:view',
  PLATFORM_WHATSAPP_MANAGE: 'platform:whatsapp:manage',
  PLATFORM_WHATSAPP_CREDENTIALS: 'platform:whatsapp:credentials',
  PLATFORM_AI_VIEW: 'platform:ai:view',
  PLATFORM_AI_MANAGE: 'platform:ai:manage',
  PLATFORM_CAMPAIGNS_VIEW: 'platform:campaigns:view',
  PLATFORM_CAMPAIGNS_MANAGE: 'platform:campaigns:manage',
  PLATFORM_AUTOMATIONS_VIEW: 'platform:automations:view',
  PLATFORM_AUTOMATIONS_MANAGE: 'platform:automations:manage',
  PLATFORM_COMMERCE_VIEW: 'platform:commerce:view',
  PLATFORM_SUPPORT_VIEW: 'platform:support:view',
  PLATFORM_SUPPORT_MANAGE: 'platform:support:manage',
  PLATFORM_ANALYTICS_VIEW: 'platform:analytics:view',
  PLATFORM_MONITORING_VIEW: 'platform:monitoring:view',
  PLATFORM_AUDIT_VIEW: 'platform:audit:view',
  PLATFORM_SETTINGS_VIEW: 'platform:settings:view',
  PLATFORM_SETTINGS_MANAGE: 'platform:settings:manage',
  PLATFORM_SUPER: 'platform:super',

  // Workspace management
  WORKSPACE_VIEW: 'workspace:view',
  WORKSPACE_MANAGE: 'workspace:manage',
  WORKSPACE_DELETE: 'workspace:delete',

  // Team & Member management
  MEMBERS_VIEW: 'members:view',
  MEMBERS_INVITE: 'members:invite',
  MEMBERS_UPDATE_ROLE: 'members:update_role',
  MEMBERS_REMOVE: 'members:remove',

  // WhatsApp Business Integration
  WHATSAPP_VIEW: 'whatsapp:view',
  WHATSAPP_CONNECT: 'whatsapp:connect',
  WHATSAPP_MANAGE: 'whatsapp:manage',

  // Conversations & Messaging
  CONVERSATIONS_VIEW: 'conversations:view',
  CONVERSATIONS_MANAGE: 'conversations:manage',
  CONVERSATIONS_ASSIGN: 'conversations:assign',
  MESSAGES_READ: 'messages:read',
  MESSAGES_SEND: 'messages:send',

  // Contacts
  CONTACTS_VIEW: 'contacts:view',
  CONTACTS_MANAGE: 'contacts:manage',
  CONTACTS_EXPORT: 'contacts:export',

  // Templates
  TEMPLATES_VIEW: 'templates:view',
  TEMPLATES_MANAGE: 'templates:manage',

  // Settings
  SETTINGS_VIEW: 'settings:view',
  SETTINGS_MANAGE: 'settings:manage',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Permission matrix mapping each workspace role to granted capabilities.
 */
export const ROLE_PERMISSIONS: Record<WorkspaceRole, readonly PermissionCode[]> = {
  [WORKSPACE_ROLES.OWNER]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.WORKSPACE_MANAGE,
    PERMISSIONS.WORKSPACE_DELETE,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.MEMBERS_INVITE,
    PERMISSIONS.MEMBERS_UPDATE_ROLE,
    PERMISSIONS.MEMBERS_REMOVE,
    PERMISSIONS.WHATSAPP_VIEW,
    PERMISSIONS.WHATSAPP_CONNECT,
    PERMISSIONS.WHATSAPP_MANAGE,
    PERMISSIONS.CONVERSATIONS_VIEW,
    PERMISSIONS.CONVERSATIONS_MANAGE,
    PERMISSIONS.CONVERSATIONS_ASSIGN,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.CONTACTS_MANAGE,
    PERMISSIONS.CONTACTS_EXPORT,
    PERMISSIONS.TEMPLATES_VIEW,
    PERMISSIONS.TEMPLATES_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  [WORKSPACE_ROLES.ADMIN]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.WORKSPACE_MANAGE,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.MEMBERS_INVITE,
    PERMISSIONS.MEMBERS_UPDATE_ROLE,
    PERMISSIONS.MEMBERS_REMOVE,
    PERMISSIONS.WHATSAPP_VIEW,
    PERMISSIONS.WHATSAPP_CONNECT,
    PERMISSIONS.WHATSAPP_MANAGE,
    PERMISSIONS.CONVERSATIONS_VIEW,
    PERMISSIONS.CONVERSATIONS_MANAGE,
    PERMISSIONS.CONVERSATIONS_ASSIGN,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.CONTACTS_MANAGE,
    PERMISSIONS.CONTACTS_EXPORT,
    PERMISSIONS.TEMPLATES_VIEW,
    PERMISSIONS.TEMPLATES_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  [WORKSPACE_ROLES.MEMBER]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.WHATSAPP_VIEW,
    PERMISSIONS.CONVERSATIONS_VIEW,
    PERMISSIONS.CONVERSATIONS_MANAGE,
    PERMISSIONS.CONVERSATIONS_ASSIGN,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.CONTACTS_MANAGE,
    PERMISSIONS.TEMPLATES_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
  ],
  [WORKSPACE_ROLES.AGENT]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.WHATSAPP_VIEW,
    PERMISSIONS.CONVERSATIONS_VIEW,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.TEMPLATES_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
  ],
  [WORKSPACE_ROLES.MANAGER]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.MEMBERS_INVITE,
    PERMISSIONS.WHATSAPP_VIEW,
    PERMISSIONS.CONVERSATIONS_VIEW,
    PERMISSIONS.CONVERSATIONS_MANAGE,
    PERMISSIONS.CONVERSATIONS_ASSIGN,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.CONTACTS_MANAGE,
    PERMISSIONS.CONTACTS_EXPORT,
    PERMISSIONS.TEMPLATES_VIEW,
    PERMISSIONS.TEMPLATES_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
  ],
  [WORKSPACE_ROLES.VIEWER]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.WHATSAPP_VIEW,
    PERMISSIONS.CONVERSATIONS_VIEW,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.TEMPLATES_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
  ],
};

// Platform role permission mapping
export const PLATFORM_ROLE_PERMISSIONS: Record<string, readonly string[]> = {
  [PLATFORM_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [PLATFORM_ROLES.PLATFORM_ADMIN]: [
    PERMISSIONS.PLATFORM_TENANTS_VIEW, PERMISSIONS.PLATFORM_TENANTS_MANAGE,
    PERMISSIONS.PLATFORM_USERS_VIEW, PERMISSIONS.PLATFORM_USERS_MANAGE,
    PERMISSIONS.PLATFORM_BILLING_VIEW, PERMISSIONS.PLATFORM_WHATSAPP_VIEW,
    PERMISSIONS.PLATFORM_AI_VIEW, PERMISSIONS.PLATFORM_CAMPAIGNS_VIEW,
    PERMISSIONS.PLATFORM_AUTOMATIONS_VIEW, PERMISSIONS.PLATFORM_COMMERCE_VIEW,
    PERMISSIONS.PLATFORM_ANALYTICS_VIEW, PERMISSIONS.PLATFORM_MONITORING_VIEW,
    PERMISSIONS.PLATFORM_AUDIT_VIEW, PERMISSIONS.PLATFORM_SETTINGS_VIEW,
  ],
  [PLATFORM_ROLES.FINANCE_ADMIN]: [
    PERMISSIONS.PLATFORM_BILLING_VIEW, PERMISSIONS.PLATFORM_BILLING_MANAGE, PERMISSIONS.PLATFORM_BILLING_REFUND,
    PERMISSIONS.PLATFORM_TENANTS_VIEW, PERMISSIONS.PLATFORM_ANALYTICS_VIEW,
  ],
  [PLATFORM_ROLES.OPERATIONS_ADMIN]: [
    PERMISSIONS.PLATFORM_WHATSAPP_VIEW, PERMISSIONS.PLATFORM_WHATSAPP_MANAGE,
    PERMISSIONS.PLATFORM_AI_VIEW, PERMISSIONS.PLATFORM_CAMPAIGNS_VIEW,
    PERMISSIONS.PLATFORM_AUTOMATIONS_VIEW, PERMISSIONS.PLATFORM_MONITORING_VIEW,
    PERMISSIONS.PLATFORM_TENANTS_VIEW, PERMISSIONS.PLATFORM_USERS_VIEW,
  ],
  [PLATFORM_ROLES.SUPPORT_ADMIN]: [
    PERMISSIONS.PLATFORM_TENANTS_VIEW, PERMISSIONS.PLATFORM_USERS_VIEW,
    PERMISSIONS.PLATFORM_SUPPORT_VIEW, PERMISSIONS.PLATFORM_SUPPORT_MANAGE,
    PERMISSIONS.PLATFORM_WHATSAPP_VIEW, PERMISSIONS.PLATFORM_AUDIT_VIEW,
  ],
};

// Aliases for uppercase access
(ROLE_PERMISSIONS as any).OWNER = ROLE_PERMISSIONS[WORKSPACE_ROLES.OWNER];
(ROLE_PERMISSIONS as any).ADMIN = ROLE_PERMISSIONS[WORKSPACE_ROLES.ADMIN];
(ROLE_PERMISSIONS as any).MANAGER = ROLE_PERMISSIONS[WORKSPACE_ROLES.MANAGER];
(ROLE_PERMISSIONS as any).MEMBER = ROLE_PERMISSIONS[WORKSPACE_ROLES.MEMBER];
(ROLE_PERMISSIONS as any).AGENT = ROLE_PERMISSIONS[WORKSPACE_ROLES.AGENT];
(ROLE_PERMISSIONS as any).VIEWER = ROLE_PERMISSIONS[WORKSPACE_ROLES.VIEWER];


export function hasPlatformPermission(
  role: string | undefined | null,
  permission: string,
): boolean {
  if (!role) return false;
  const normalized = (role as string).toLowerCase();
  const granted = PLATFORM_ROLE_PERMISSIONS[normalized] || PLATFORM_ROLE_PERMISSIONS[(role as string).toUpperCase()] || PLATFORM_ROLE_PERMISSIONS[role];
  if (!granted) {
    // super_admin bypass
    if (normalized === 'super_admin' || normalized === 'admin') return true;
    return false;
  }
  return (granted as readonly string[]).includes(permission) || (granted as readonly string[]).includes(PERMISSIONS.PLATFORM_SUPER);
}

/**
 * Checks if a specific workspace role is granted a given permission.
 */
export function hasPermission(
  role: WorkspaceRole | string | undefined | null,
  permission: PermissionCode,
): boolean {
  if (!role) return false;
  const normalized = (role as string).toUpperCase() as WorkspaceRole;
  const granted = ROLE_PERMISSIONS[normalized] || ROLE_PERMISSIONS[(role as string).toLowerCase() as WorkspaceRole];
  if (!granted) return false;
  return granted.includes(permission);
}

/**
 * Returns all permission codes granted to the role.
 */
export function getPermissionsForRole(
  role: WorkspaceRole | string | undefined | null,
): PermissionCode[] {
  if (!role) return [];
  const normalized = (role as string).toUpperCase() as WorkspaceRole;
  return [...(ROLE_PERMISSIONS[normalized] || ROLE_PERMISSIONS[(role as string).toLowerCase() as WorkspaceRole] || [])];
}
